name: build-and-test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  PRIMARY_NODE_VERSION: 24

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
          cache: yarn

      - name: Yarn
        run: yarn install --ignore-scripts

      - name: ESLint
        run: yarn lint

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-22.04
          - windows-latest
        node:
          - 20
          - 22
          - 24
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Prepare environment
        id: prepare-env
        if: runner.os != 'Windows'
        run: |
          # make directories
          mkdir -p deps/curl-impersonate/build

          # define variables
          os=$(node -e 'console.log(process.platform)')
          arch=$(node -e 'console.log(process.arch)')

          cd deps/curl-impersonate
          curl_impersonate_commit=$(git rev-parse HEAD)
          curl_impersonate_tag=$(git describe --abbrev=0 --tags 2>/dev/null | sed -E 's/^(v?[0-9]+)\./\1./' || echo '')
          curl_impersonate_ref=$curl_impersonate_tag
          if [[ "$curl_impersonate_ref" == "" ]]; then
            curl_impersonate_ref=${curl_impersonate_commit:0:7}
          fi
          curl_impersonate_cache_key="build-cache-${{ runner.os }}-$arch-curl-impersonate-$curl_impersonate_commit"
          curl_impersonate_artifact="curl-impersonate-$curl_impersonate_ref-$os-$arch"
          cd - >/dev/null

          # append commit to package.json version
          commit=$(git rev-parse HEAD)
          pkgver=$(sed -nE 's/.*"version": *"([^"]+)".*/\1/p' package.json)
          pkgver="$pkgver-${commit:0:7}"
          sed -i.bak -E 's/(.*"version": *)"[^"]+"/\1"'"$pkgver"'"/' package.json
          rm -f package.json.bak

          node_abi="node-v$(node -e 'console.log(process.versions.modules)')"
          binding_artifact=node_libcurl_ja3-v$pkgver-$node_abi-$os-$arch

          # write variables to parse as output
          cat <<EOF >> "$GITHUB_OUTPUT"
          curl_impersonate_cache_key=$curl_impersonate_cache_key
          curl_impersonate_artifact=$curl_impersonate_artifact
          pkgver=$pkgver
          binding_artifact=$binding_artifact
          package_artifact=node-libcurl-ja3-v$pkgver
          EOF
          echo "PKGVER=$pkgver" >> "$GITHUB_ENV"
          echo "BINDING_ARTIFACT=$binding_artifact" >> "$GITHUB_ENV"
          echo "PACKAGE_ARTIFACT=node-libcurl-ja3-v$pkgver" >> "$GITHUB_ENV"
      - name: Prepare environment (Windows)
        if: runner.os == 'Windows'
        id: prepare-env-win
        shell: pwsh
        run: |
          $commit = (git rev-parse HEAD)
          $pkgver = (Get-Content package.json -Raw | ConvertFrom-Json).version
          $pkgver = "$pkgver-$($commit.Substring(0,7))"
          $packageJson = Get-Content package.json -Raw | ConvertFrom-Json
          $packageJson.version = $pkgver
          $packageJson | ConvertTo-Json -Depth 100 | Set-Content package.json
          $os = node -e "console.log(process.platform)"
          $arch = node -e "console.log(process.arch)"
          $node_abi = node -e "console.log('node-v' + process.versions.modules)"
          $binding_artifact = "node_libcurl_ja3-v$pkgver-$node_abi-$os-$arch"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "pkgver=$pkgver"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "binding_artifact=$binding_artifact"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "package_artifact=node-libcurl-ja3-v$pkgver"
          Add-Content -Path $env:GITHUB_ENV -Value "PKGVER=$pkgver"
          Add-Content -Path $env:GITHUB_ENV -Value "BINDING_ARTIFACT=$binding_artifact"
          Add-Content -Path $env:GITHUB_ENV -Value "PACKAGE_ARTIFACT=node-libcurl-ja3-v$pkgver"

      # changes timestamps for files in the curl-impersonate submodule to their git mtime
      # to allow the build cache to work, else it will think all files have been modified
      - if: runner.os != 'Windows'
        name: Restore curl-impersonate timestamps
        uses: chetan/git-restore-mtime-action@v2
        with:
          working-directory: deps/curl-impersonate

      - if: runner.os != 'Windows'
        name: Restore curl-impersonate build cache
        id: libcurl-build-cache
        uses: actions/cache@v4
        with:
          path: deps/curl-impersonate/build
          key: ${{ steps.prepare-env.outputs.curl_impersonate_cache_key }}

      - if: runner.os == 'Linux'
        name: Install build packages on Linux
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo -E apt update -qqy
          sudo -E apt install -qqy autoconf automake build-essential cmake curl libtool ninja-build pkg-config

      - if: runner.os == 'macOS'
        name: Install build packages on macOS
        run: brew install automake bash libtool make meson ninja

      - name: Yarn
        run: npm_config_build_from_source=true yarn install --frozen-lockfile

      - name: Build
        run: yarn build:dist

      - if: runner.os != 'Windows'
        name: Get curl-impersonate version
        run: |
          deps/curl-impersonate/build/curl-impersonate/bin/curl-impersonate --version | grep -v unreleased | sed -E 's/^(curl [^ ]+) \([^)]+\)/Versions: \1/'

      - if: runner.os == 'Linux'
        name: Check Linux binary does not dynamically link libraries
        run: |
          libs=$(
            ldd deps/curl-impersonate/build/curl-impersonate/bin/curl-impersonate \
              | sed -nE 's/\s*(.+?)\.so(\.[0-9]+)? => .+/\1/p' \
              | grep -wvE 'libc|libgcc_s|libm|libstdc\+\+' \
              | tr $'\n' ' ' | sed -E 's/ +$//' \
            )
          if [[ "$libs" != "" ]]; then
            echo "error: unexpected linked libraries: $libs" >&2
            exit 1
          fi

      - if: runner.os == 'macOS'
        name: Check macOS binary does not dynamically link libraries
        run: |
          libs=$(
            otool -L deps/curl-impersonate/build/curl-impersonate/bin/curl-impersonate \
              | sed -nE 's/\t(.+) \(.+/\1/p' \
              | grep -vE '^(/System/Library/|/usr/lib/)' \
              | tr $'\n' ' ' | sed -E 's/ +$//' \
            )
          if [[ "$libs" != "" ]]; then
            echo "error: unexpected linked libraries: $libs" >&2
            exit 1
          fi

      - name: Pretest
        run: yarn test --testNamePattern='^Browser Impersonation' test/curl/impersonate.spec.ts

      - if: runner.os != 'Windows'
        name: Rename curl-impersonate build tarball
        run: mv deps/curl-impersonate/build/curl-impersonate.tar.gz 'build/${{ steps.prepare-env.outputs.curl_impersonate_artifact }}.tar.gz'

      - if: matrix.node == '24'
        name: Upload curl-impersonate build tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepare-env.outputs.curl_impersonate_artifact }}.tar.gz
          path: build/${{ steps.prepare-env.outputs.curl_impersonate_artifact }}.tar.gz
          if-no-files-found: error

      - name: Delete curl-impersonate build tarball
        run: rm -f build/${{ steps.prepare-env.outputs.curl_impersonate_artifact }}.tar.gz

      - name: Create native binding tarball
        shell: bash
        run: |
          mkdir -p build
          tar -czf "build/${{ env.BINDING_ARTIFACT }}.tar.gz" -C lib/binding/Release .

      - name: Upload native binding tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINDING_ARTIFACT }}.tar.gz
          path: build/${{ env.BINDING_ARTIFACT }}.tar.gz
          if-no-files-found: error

      - if: runner.os == 'Linux' && matrix.node == '24'
        name: Create package tarball
        run: |
          npm pack
          pkgver='${{ env.PKGVER }}'
          tar xf "node-libcurl-ja3-$pkgver.tgz" -C build
          rm -f "node-libcurl-ja3-$pkgver.tgz"
          cd build
          mv package node-libcurl-ja3
          tar zcf '${{ env.PACKAGE_ARTIFACT }}.tar.gz' node-libcurl-ja3

      - if: runner.os == 'Linux' && matrix.node == '24'
        name: Upload package tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_ARTIFACT }}.tar.gz
          path: build/${{ env.PACKAGE_ARTIFACT }}.tar.gz
          if-no-files-found: error

      - name: Test
        run: yarn test
